"""empty message

Revision ID: 2f98b4debd80
Revises: 2f8ef00281b0
Create Date: 2026-03-05 17:13:14.876697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f98b4debd80'
down_revision = '2f8ef00281b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint('characters_height_key', type_='unique')
        batch_op.drop_constraint('characters_name_key', type_='unique')
        batch_op.drop_constraint('characters_race_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.create_unique_constraint('characters_race_key', ['race'])
        batch_op.create_unique_constraint('characters_name_key', ['name'])
        batch_op.create_unique_constraint('characters_height_key', ['height'])

    # ### end Alembic commands ###
